name: breaking_bad_bloc_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  animated_text_kit: ^4.2.1
  bloc: ^8.0.2
  buildcondition: ^0.0.4
  #dio: ^4.0.4
  http: ^0.13.4
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.3.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
